version: '3'
services:
  api:
    build: services/api
    environment:
      - PORT=80
      - DATABASE_URL=postgres://test:test@db:5432/wardrobe
    ports:
    - 8080:80
    volumes:
      - ./src/api:/srv/code/
  db:
    image: postgres:9.6
    volumes:
    - ./migration/:/migration/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test