version: '3'
services:
  api:
    build: services/api
    environment:
      - PORT=80
      - DATABASE_URL=postgres://test:test@db:5432/taberu
    ports:
    - 8080:80
    volumes:
      - ./src/api:/srv/code/
    working_dir: /srv/code/
  composer:
    image: composer:2.1.3
    volumes:
      - ./src/api:/app
  app:
    build: services/frontend
    environment:
      - PORT=80
    ports:
    - 1337:80
    volumes:
      - ./src/frontend/:/node
  db:
    image: postgres:9.6
    volumes:
    - ./migration/:/migration/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test
  node:
    image: node:16.5-slim
    volumes:
    - ./src/frontend:/app/
    working_dir: /app
  proxy:
    image: nginx:1.19.10-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./services/proxy/certs:/etc/nginx/certs
    depends_on:
      - app
      - api